[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["node_modules"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
fs_permissions = [
    { access = "read-write", path = "./" },
    { access = "read", path = "../bond-shared-registry" },
    { access = "read", path = "../../bond-shared-registry" },
]
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "@pythnetwork/=node_modules/@pythnetwork/",
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/ds-test/src/",
]
